# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sample_blog_2',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/sample_blog_2',
                'lib_path': 'sample_blog_2'},
  'syms': { 'sample_blog_2.basics': { 'sample_blog_2.basics.foo': ('core.html#foo', 'sample_blog_2/basics.py'),
                                      'sample_blog_2.basics.my_first_function': ('core.html#my_first_function', 'sample_blog_2/basics.py')},
            'sample_blog_2.core': { 'sample_blog_2.core.foo': ('core.html#foo', 'sample_blog_2/core.py'),
                                    'sample_blog_2.core.my_first_function': ('core.html#my_first_function', 'sample_blog_2/core.py')}}}
