# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'my_first_function']

# %% ../nbs/00_core.ipynb 3
def foo(): pass

def my_first_function():
    """Simple greeter."""
    print("Hello, world!")
